### ISSUE TITLE
Audio / Video ofset

### ISSUE THREAD

**Issue by LaciStrike** [AntonyCorbett/OnlyM#219] opened 2019-02-13 20:35 UTC
Hi, 
first of all, thank you so much for this program. It's great.
Unfortunately, in past few days, we experienced some issues with the program compatibility.
As we used this program previously with Windows 10, build 1607 and FrameNet 4.7.2, everything worked well and smooth. But after Windows update to Build 1803 and higher version of FrameNet, program started to freeze during video playback, or an big offset between audio and video output occured (.mp4 format). 
This happens randomly (one or two songs played well, third bad, or first OK, second bad, third OK, ...)

We could confirm on another CPU, that using older version of WIN 10 works, and updating to Build 1803 immediatelly lead to crushing of the program.
That's all we've investigated till now.
Do you have any ideas, what we could change (except Windows downgrade as it would upgrade later again :D ) or did you already experienced this kind of issue from other users?
Thanks or your support

**Comment by LvDaniel** [comment] 2019-02-13 20:57
@LaciStrike I'm using build 1803 at home with no issues. At KH we're using build 1809 and everything works fine.
At home I have. NET Framework 4.7.03056.

**Comment by AntonyCorbett** [comment] 2019-02-13 21:52
@LaciStrike Windows updates commonly cause problems because they replace the video and/or audio driver. The solution is usually to either rollback the driver (usually the video one) to the previous setting, or to update it with reference to the manufacturer's website (rather than via Windows Update).

**Comment by AntonyCorbett** [comment] 2019-02-13 21:54
@LaciStrike I'm using 1809 now but used 1803 for a long time.

**Comment by LaciStrike** [comment] 2019-02-14 17:39
Thanks for the feedback. I was thinking the same (more or less), but didn'try it yet. Will check it later in KH, if those drivers were updated as well. Was just confused, as the symptoms were the same on 2 separate computers with different HDW configurations.
Will feedback once I'll have more info related to this.
Thank you :)

**Comment by shbin1** [comment] 2019-02-19 16:10
Last month we had terrible trouble with Win 10 build 1809 with similar symptoms, it also changed the ordering of our 3 displays. Our video card is an Nvidia and we had to update the driver AND the display order and graphics CPU to PC CPU to get it to work reliably displaying lyrics and playing sound. Also any new desktop icons appear on the first extended screen.

**Comment by AntonyCorbett** [comment] 2019-03-07 10:32
@LaciStrike closing now but please reopen if the issue is ongoing

**Closed by AntonyCorbett** 2019-03-07 10:32 UTC
Labels: question

**Comment by LaciStrike** [comment] 2019-03-07 16:31
Hi, thanks.
We'r still observing it, but for now, it seems, it stopped from itself (or Jehovah caused it to stop) 😊
Thank you for your support

**Comment by LaciStrike** [comment] 2019-05-26 09:44
> Hello Antony,  
have some issues to log in into GitHub, so I write you like this.  
Ive realized, that with OmlyM while running together with JW Library,
after media is played in OnlyM and switched off again (or video playback
finishes), sometimes the years text comming from JW Library isnt
displayed at main monitor again, only black screen. We need to re-start
JW Library, to display it again.  
Any ideas, why this happens?  
Thanks for your support  
  
Ladislav - Slovakia - Hlohovec Congregation :)

**Comment by AntonyCorbett** [comment] 2019-05-26 12:07
Use "JwlMediaWin" to fix the JWL media window.
