### ISSUE TITLE
Bible Text Image tool

### ISSUE THREAD

**Issue by Jeremy909** [AntonyCorbett/OnlyM#15] opened 2018-06-05 19:02 UTC
We had been using the SoundBox Bible Text Image Creator for a long time. Now we have switched to using Only-M alongside JW Library, is it possible to include it in Only-M so we can continue using it?

**Comment by AntonyCorbett** [comment] 2018-06-05 19:08
You can use it already by dragging the image from the Bible Text Image tool onto OnlyM. Just click and drag on the image in the window. I may make some modifications too.

**Comment by Jeremy909** [comment] 2018-06-05 19:20
Thanks for the suggestion. I just tried it and it works ok that way. I guess I have to keep Soundbox installed to use it for now.

**Comment by Chipperchap** [comment] 2018-06-09 23:00
HI Antony,
Thank you for your OnlyM program.
Just had a play with the BTIT onto OnlyM and if the scripture is rendered as a folder (a scripture with more than one screen of text such as multiple verses) then OnlyM will not copy over.  The images have to be separated into individual images first (done by opening the OnlyM folder and dragging the images out into the folder as individual pages / images.)  See silent video [HERE](https://youtu.be/Ibe5uqBESMM).  Please, is there a work-around for this or have I already found the only work-around?

**Comment by gonzo041** [comment] 2018-08-01 12:38
Good morning, I consult you when there are updates in the Bible, since in Spanish we still do not have the revised version, you will update it ?. Sorry for my English.

**Comment by AntonyCorbett** [comment] 2018-08-01 12:54
@gonzo041 it should automatically update in the application a few days after release.

**Comment by gonzo041** [comment] 2018-08-03 15:32
Dear Antony,
In our congregation we often project the conference of the weekend meeting by streaming, with which I consult you if it is possible that the OnlyM application allows you to superimpose the image of the biblical text to the video.
Today with the reproduction of a sound file it can be superimposed, but with the reproduction of video it can not be.

**Comment by AntonyCorbett** [comment] 2018-08-03 17:25
@gonzo041 In more general terms, I think your idea is that we should allow an image to take over the display while the video remains playing and the audio track remains audible. Correct?

**Comment by gonzo041** [comment] 2018-08-03 17:41
Exactly! The idea is that when the speaker quotes a biblical text we can project the image of it.

**Comment by AntonyCorbett** [comment] 2018-08-03 17:45
@gonzo041 please see #33. I'll delete the last few posts from this issue as they aren't directly relate.

**Comment by AntonyCorbett** [comment] 2018-09-27 12:37
@Jeremy909 OnlyV is now available so closing this issue

**Closed by AntonyCorbett** 2018-09-27 12:37 UTC
Labels: enhancement
