### ISSUE TITLE
Multiple Slide Shows in OnlyM

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyM#291] opened 2019-10-30 01:48 UTC
I was preparing 2 slide shows for our meeting this week. I dragged my photos for the first slide show into the OnlyM Slide Manager and saved the .omslide file to my desktop. I did the same for the second slide show. Then, I uploaded both .omslide files into OnlyM. The first slide show played normally, however, when I tried to play the second, I noticed it was playing the slides from the first one! So now I have 2 .omslide files in OnlyM playing the same slides. I thought I did something wrong with creating the slide files so I created them again, but the same issue was happening. I was finally able to get the second one to play by deleting the first one from OnlyM, and then closing and re-opening OnlyM. Both thumbnails in OnlyM for the files are different and showing the correct content. The issue comes when I start playing them. A simple workaround for me would be to combine all the slides into one presentation, but I was wondering if this is something that could be fixed.

**Comment by AntonyCorbett** [comment] 2019-10-30 17:54
@scottys94 Hi. Thanks for your report. I can't reproduce this yet so wonder if I am missing a step. Can I check the OnlyM version you are using please? And if you have any further suggestions on how to reproduce the issue that would be appreciated.

**Comment by scottys94** [comment] 2019-10-30 23:04
@AntonyCorbett I am using version 1.5.0.19 of OnlyM. It seems like I was able to narrow down the issue further. The presentation started in PowerPoint. From PowerPoint, I went to Save As and selected the JPEG file format. Then I took the JPEG files and uploaded them into the OnlyM Slide Manager. So the issue is only happening with JPEG's created from PowerPoint slides. I tried again with another PowerPoint presentation, and the same issue was happening. However, when I tried creating multiple OnlyM slides with other pictures (taken from my phone, for example), the issue was not happening. I am using the PowerPoint included with Office 365.

**Comment by AntonyCorbett** [comment] 2019-10-31 22:34
@scottys94 I have been able to reproduce the issue but it has to do with the use of the Slide Manager and is unrelated to Powerpoint. The bug can be described as follows: Having saved a slideshow ("A") in Slide Manager you must close down Slide Manager before beginning a new slideshow ("B") otherwise the slides from "A" will also appear in "B"! i.e. the "New slideshow" button doesn't properly purge the existing slides.

**Comment by AntonyCorbett** [comment] 2019-11-02 20:39
@scottys94 Now fixed

**Comment by scottys94** [comment] 2020-03-08 17:20
Hi Antony,
Thank you for working on this issue a while ago. Unfortunately, it turns out the issue is still happening. I have attached the PowerPoint files used to create the slides, as well as the .omslide files. I closed down the Slide Manager after creating the first slideshow. When I upload both .omslide files to OnlyM and try to play them, they both seemed to have "merged" with each other. Some slides from one slideshow have been replaced with the other slideshow.
[Slideshow Files.zip](https://github.com/AntonyCorbett/OnlyM/files/4303559/Slideshow.Files.zip)

**Comment by AntonyCorbett** [comment] 2020-03-08 18:16
@scottys94 Please reduce the problem to as simple a case as possible. Would you send me individual image files (to remove the possibility of mistakes made while extracting the images from ppt) stipulating which ones go in which slideshow and the steps you take to create the 2 slideshows. Thanks for your help.

**Comment by scottys94** [comment] 2020-03-13 03:04
@AntonyCorbett It looks like I was finally able to narrow down this issue significantly. Here is what I was doing. I created a folder on my desktop, and I named it "Images for Slide 1". I had 3 JPEG image files in that folder. The image files were named as follows: Image1, Image2, Image3. I uploaded these 3 files into the Slide Manager, created a slideshow, saved the .omslide file on my desktop as Slideshow-1, and closed the Slide Manager. Then I created a second folder on my desktop named "Images for Slide 2". I put 3 different JPEG image files into this folder, and the image files were also named as follows: Image1, Image2, Image3. I opened the Slide Manager and uploaded these 3 files. I saved the .omslide file on my desktop as Slideshow-2. Then, I upload both .omslide files into OnlyM - Slideshow-1 and Slideshow-2. I finally realized this issue was happening because: The source file names for the image files were the same - when I was creating the slideshows. For the second set of images (the ones I put in the "Images for Slide 2" folder), if I rename them as Image4, Image5, Image6, and repeat the same steps, the issue does not occur. Both slideshows play normally in this case. Please let me know if you need any additional details.

**Comment by AntonyCorbett** [comment] 2020-03-13 08:45
@scottys94 - thanks, that helpful. The bug is in OnlyM which caches the slides images according to their name (without regard to the slideshow they are in).

**Closed** 2020-03-13 09:01 UTC
Labels: bug
