### ISSUE TITLE
When I try to play any videos, it just shows a black screen. I can hear the audio.

### ISSUE THREAD

**Issue by vertigo3d** [AntonyCorbett/OnlyM#321] opened 2020-03-19 19:02 UTC
When I try to play any videos, it just shows a black screen. I can hear the audio.

Windows 10 (x64) Pro

I can play files in VLC without a problem.

**Comment by AntonyCorbett** [comment] 2020-03-19 19:41
This is usually caused by an outdated video driver. Please update it using the manufacturer's website rather than relying on Windows update.

**Comment by AntonyCorbett** [comment] 2020-04-01 19:12
Closing for now but reopen if you can't resolve it

**Closed by AntonyCorbett** 2020-04-01 19:12 UTC
