### ISSUE TITLE
Monitor settings keep getting reset.

### ISSUE THREAD

**Issue by webnoob** [AntonyCorbett/OnlyM#276] opened 2019-08-25 10:24 UTC
**Describe the bug**
Quite often, only M is losing it's monitor settings and we're having to reset them. This is fine for our techy users but for the not so techy ones, it's proving difficult.

How are the settings stored? Is it an internal DB, registry, file?

**To Reproduce**
I don't know exactly. I know it's happened after windows updates. We have 2 users on our computer (one for each congregation) so this might be impacting it.

**Expected behavior**
The monitors to remain in place once the setting has been set.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 10
- 2 Users (one for each congregation).

Note: This issue also affects onlyT - If I could have some information as to how the settings are stored, I could write a small app our users could click on to reset the settings to what we need so even if this can't be "fixed" - information on storage would be great.

Edit: Ok, got the settings: https://github.com/AntonyCorbett/OnlyM/blob/3cf4c5934af070d7724674d8a2fadad730727ba8/OnlyM.Core/Services/Options/OptionsService.cs#L324

`C:\Users\<user>\AppData\Roaming\OnlyM\1\options.json`

Given I know this is the save path now, I can try and debug it myself locally and see if the files are being overwritten somehow. For now, I'll create a default file it can be overwritten with and create a small batch file to sort it.

**Comment by webnoob** [comment] 2019-08-25 11:16
I've written a small batch file to get around this for now, in case this is useful to anyone else, here it is:

```batch
@echo off
REM The location of our default files which will map to something like C:\DefaultsForMediaSettings\OnlyM\1\options.json
SET SAVE_PATH=C:\DefaultsForMediaSettings

REM The program settings we want to overwrite. To add another, 
REM 1. Add it to the list below (in the same format)
REM 2. Add a new folder in %SAVE_PATH% (in the same format).
SET LOCATIONS=OnlyM
SET LOCATIONS=%LOCATIONS%;OnlyT
SET LOCATIONS=%LOCATIONS%;OnlyV

echo Please close OnlyM, OnlyT, OnlyV and then press any key to continue...
pause

REM Loop through our apps that need resetting and copy the defualt files to the new location.
FOR %%p IN (%LOCATIONS%) DO (
	echo Resetting %%p
	copy "%SAVE_PATH%\%%p\options.json" "%appdata%\%%p\1\options.json" /y
)

echo All settings have been reset, you can now open OnlyM, OnlyT and OnlyV (where applicable).
pause
```

**Comment by AntonyCorbett** [comment] 2019-08-25 13:08
@webnoob thanks for your report. The settings are recalled from the options file as you deduced above. The unintended swapping of monitors is sometimes caused by the EDID data being unavailable when OnlyM opens (sometimes the case when using HDMI or SDI switches). If a monitor is not available then OnlyM will leave the media monitor field empty. EDID emulators are sometimes used to overcome this. Not sure if this is what you are seeing. What version of OnlyM are you using please?

**Comment by webnoob** [comment] 2019-08-25 16:45
Thanks for the response Antony. I think we're using the latest version - I'll have to confirm after Tueday.

We had a big melt down today where none of the monitors were working properly (Even in windows) so I'm not sure it's isolated to OnlyM. The EDI switch idea might be the problem though as we have OnlyM starting with windows.

For now, I'll stop them starting with windows - hopefully that'll give things time to register before OnlyM starts.

I'll report back when I can.

**Comment by AntonyCorbett** [comment] 2019-08-31 09:33
@webnoob closing for now, but feel free to add comments

**Closed by AntonyCorbett** 2019-08-31 09:33 UTC
Labels: question
