### ISSUE TITLE
Screenshare not working simultaneously with background music

### ISSUE THREAD

**Issue by MDGitHubing** [AntonyCorbett/OnlyM#413] opened 2021-08-24 08:59 UTC
**Describe the bug**

I want to share screen (Zoom) and play audio from JW Library, the same time an image is opened on OnlyM. Before this was possible. However now music doesn't play from JW Library if onlyM is opened - either you can't hear it or the music just doesn't play.  

**To Reproduce**

1. Open OnlyM and JW Library 
2. Play OnlyM image on second screen.
3. Share second screen on Zoom, ensure optimise video and share sound screen ticked. 
3. Start playing music from JW Library
4. Music doesn't play; should be able to play music same time screen is being shared on second screen

**Expected behavior**

These steps can be followed in different order, still doesn't work for me

**Desktop (please complete the following information):**
 - Windows 10
 
 Not sure issue with Zoom. Thanks!!

**Comment by scottys94** [comment] 2021-08-25 01:56
Which version of Zoom are you using?

**Comment by MDGitHubing** [comment] 2021-08-29 00:19
Zoom Version 5.7.4 (804)

**Comment by jonathanmoss98** [comment] 2021-10-04 09:46
We have noticed this same type of issue in our congregation too. It happens even if Zoom is not running though, so I dont think it is Zoom related specifically (at least based on my testing)

OnlyM version: 2.0.0.11
JW Library version: 12.4.152 (115081)

**To reproduce on system with two screens:**
Open JW Library with play video on second display option enabled
Open OnlyM with output on same screen as JW Library output and JW compatibility mode enabled
Start static image playing in OnlyM (ours is a message about breakout rooms, but could be any image)
Open media for given meeting and select opening song

**Result:**
Song does not start playing

To kick it along, stop OnlyM image playing and then start again.
Image disappears and re-appears, and JW Library media starts playing.

If playing audio only files in JW library before the meeting for example, same type of issue is evident, however, as there is no video playing, it's less obvious that the media has not started to play. So the media brother must either stop and start the image display in OnlyM at the end of each song or not have an image displayed and just show the JW Library year text.

I also noticed something strange when doing some training with a new media brother over Zoom. When this playback issue was occurring, it seemed like his computer audio was stopped, so he could not hear me on Zoom either. It was not until we stopped and started OnlyM image playback that he could hear me again. I'm sure it is related, but not sure exactly how.

If I can provide any logs or system information, please let me know, happy to help diagnose this if I can. I cant seeing anything related in any of the event logs.

I am on a Dell laptop with external screen over HDMI connection running Windows 10 fully updated.

Regards, Jonathan

**Comment by jonathanmoss98** [comment] 2022-01-09 00:57
As a follow up to this issue, I have discovered this issue occurs not just with OnlyM, but with PowerPoint as well, whereby if a PP slide is open in presenter mode and displayed on the same screen as the JW Library media window, the music will not start playing for a new song until the media window is activated. Once it is activated, the music starts and it is possible to switch back to the PP slide. So I am suspecting that the issue is actually with the JW Library media window on the second display rather than OnlyM

**Comment by MDGitHubing** [comment] 2022-03-17 09:12
Yes, seems to be the case

**Comment by AntonyCorbett** [comment] 2024-08-29 13:38
Closing. This is a JW Library limitation

**Closed by AntonyCorbett** 2024-08-29 13:38 UTC
