### ISSUE TITLE
Only M crashing

### ISSUE THREAD

**Issue by antonylow** [AntonyCorbett/OnlyM#349] opened 2020-05-22 03:20 UTC
**Describe the bug**
Hello, thank you so much for this program very helpful!

I keep having the issue of the program crashing. Displaying pictures is fine. But when i play videos 80% of the time it is fine, then then the other 20% the program freezes then crashes with a "program not responding" message in the bar at the top of the Only M program. I've tried it with the Jw app open and closed but same result. I have updated to latest version. And have reinstalled but problem still happening. Please help.

**To Reproduce**
3. See error

**Expected behavior**
**For it not to crash**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version - **Windows 10 Home**
 - Other important information about your environment

**Comment by AntonyCorbett** [comment] 2020-05-22 06:28
@antonylow are you using “windowed” mode with the window on a secondary monitor? If so, it's likely the Microsoft rendering bug (see wiki). Solution is to use ffmpeg rendering mode. 
Regards, Antony

**Comment by antonylow** [comment] 2020-05-22 07:13
Hey, 

Thanks for getting back to me. I have now idea how make that solution happen. Any other advise?

Thanks
Antony

**Comment by AntonyCorbett** [comment] 2020-05-22 08:39
@antonylow Can you confirm that the problem only happens in windowed mode when rendered on a secondary display? If so, then go into OnlyM Settings and choose the "FFMPEG" render mode. See the wiki for further details if needed. Regards, Antony

**Comment by antonylow** [comment] 2020-05-22 09:25
Sorry, yes using a second screen (in extend mode) 
And sorry for my inexperience, but when you say "wiki" are you talking about wikiapedia?

Thanks again

**Comment by AntonyCorbett** [comment] 2020-05-22 10:58
@antonylow np. The wiki is part of this project on GitHub and contains the OnlyM documentation:

https://github.com/AntonyCorbett/OnlyM/wiki

Here's the extract regarding the bug I think you are experiencing:

NOTE: When using windowed mode, OnlyM will fail to render the H.264 video codec on some display drivers when the media window is enitrely outside of the pimary display device. This is caused by a bug in the Microsoft WPF framework and it can mean OnlyM crashes when playing mp4 files in windowed mode on a secondary monitor. If you experience this, one solution is to use the FFMPEG rendering engine (see Settings | Video). Another solution is to launch OnlyM with the "--nogpu" command-line parameter.

**Comment by AntonyCorbett** [comment] 2020-06-14 17:24
@antonylow I am closing the issue now. Please reopen if my response didn't provide enough information.

**Closed by AntonyCorbett** 2020-06-14 17:24 UTC
