### ISSUE TITLE
Crash on Opening

### ISSUE THREAD

**Issue by Jemmuel13** [AntonyCorbett/OnlyM#188] opened 2019-01-15 15:27 UTC
Sir may i ask whats the problem, I cant run the app everytime i open the app it crash.. but when i use the older ver. it works well(1.1.0.25) btw im using win7 home premium..

**Comment by LvDaniel** [comment] 2019-01-15 15:36
@Jemmuel13 you can check the logs, maybe they throw some light.
Can be found in Documents\OnlyM\Logs.

**Comment by Jemmuel13** [comment] 2019-01-15 15:46
Try it but my logs are empty..to be specific i cant go to the User Interface of the app.. it say onlyM has stop working. but onlyV and onlyT is working with its latest release..

**Comment by AntonyCorbett** [comment] 2019-01-15 16:11
@Jemmuel13 perhaps your anti-virus has interefered with the installation.

**Comment by Jemmuel13** [comment] 2019-01-15 16:14
@AntonyCorbett I turned off my antivirus when i installed it..

**Comment by Jemmuel13** [comment] 2019-01-15 16:32
![picture1](https://user-images.githubusercontent.com/46718159/51194439-07185e80-1926-11e9-8ff2-3be142df484d.png)
@AntonyCorbett this is the window that popup when i open the app.

**Comment by AntonyCorbett** [comment] 2019-01-15 16:41
@Jemmuel13 Please can you send me any Windows event viewer entries associated with the crash?

**Comment by Jemmuel13** [comment] 2019-01-15 16:48
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: OnlyM.exe
P2: 1.4.0.6
P3: 5c307771
P4: OnlyM
P5: 1.4.0.6
P6: 5c307771
P7: 7
P8: 31
P9: System.IO.FileNotFoundException
P10: 

Attached files:

These files may be available here:
C:\Users\JEMMUEL\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_OnlyM.exe_5379bd206caeea896da12a6369bf7727015f479_09703f05

Analysis symbol: 
Rechecking for solution: 0
Report Id: 947412df-18e2-11e9-803f-b870f4af105e

@AntonyCorbett is that it?

**Comment by Jemmuel13** [comment] 2019-01-15 16:52
Faulting application name: OnlyM.exe, version: 1.4.0.6, time stamp: 0x5c307771
Faulting module name: KERNELBASE.dll, version: 6.1.7601.17514, time stamp: 0x4ce7b8f0
Exception code: 0xe0434352
Fault offset: 0x0000b760
Faulting process id: 0x152c
Faulting application start time: 0x01d4acf29ddc1585
Faulting application path: C:\Program Files\OnlyM\OnlyM.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: dce6495d-18e5-11e9-803f-b870f4af105e
@AntonyCorbett

**Comment by AntonyCorbett** [comment] 2019-01-15 17:35
@Jemmuel13 Thanks - yes that's it. It's a "file not found" exception, but I don't know which one. Would you kindly send me the crash report file from the cited location? C:\Users\JEMMUEL\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_OnlyM.exe_5379bd206caeea896da12a6369bf7727015f479_09703f05

**Comment by Jemmuel13** [comment] 2019-01-15 23:47
@AntonyCorbett i cant send the file because the attachment does not support its file format. if you want to know the txt inside it, here it is:

Version=1
EventType=CLR20r3
EventTime=131920433054961344
ReportType=2
Consent=1
ReportIdentifier=947412e0-18e2-11e9-803f-b870f4af105e
IntegratorReportIdentifier=947412df-18e2-11e9-803f-b870f4af105e
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=OnlyM.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.4.0.6
Sig[2].Name=Problem Signature 03
Sig[2].Value=5c307771
Sig[3].Name=Problem Signature 04
Sig[3].Value=OnlyM
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.4.0.6
Sig[5].Name=Problem Signature 06
Sig[5].Value=5c307771
Sig[6].Name=Problem Signature 07
Sig[6].Value=7
Sig[7].Name=Problem Signature 08
Sig[7].Value=31
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.IO.FileNotFoundException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.768.3
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0a9e
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0a9e372d3b4ad19135b953a78882e789
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=0a9e
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=0a9e372d3b4ad19135b953a78882e789
UI[2]=C:\Program Files\OnlyM\OnlyM.exe
UI[3]=OnlyM has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\OnlyM\OnlyM.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\system32\KERNEL32.dll
LoadedModule[4]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\system32\msvcrt.dll
LoadedModule[7]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[8]=C:\Windows\system32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[11]=C:\Windows\system32\GDI32.dll
LoadedModule[12]=C:\Windows\system32\USER32.dll
LoadedModule[13]=C:\Windows\system32\LPK.dll
LoadedModule[14]=C:\Windows\system32\USP10.dll
LoadedModule[15]=C:\Windows\system32\IMM32.DLL
LoadedModule[16]=C:\Windows\system32\MSCTF.dll
LoadedModule[17]=C:\Windows\system32\VERSION.dll
LoadedModule[18]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[19]=C:\Windows\system32\MSVCR120_CLR0400.dll
LoadedModule[20]=C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\97e047cf68e9a7d90e196d072cd49cac\mscorlib.ni.dll
LoadedModule[21]=C:\Windows\system32\ole32.dll
LoadedModule[22]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[23]=C:\Windows\system32\uxtheme.dll
LoadedModule[24]=C:\Program Files\UX Pack\YzShadow\YzShadow.dll
LoadedModule[25]=C:\Program Files\UX Pack\LeftSider\leftsider.dll
LoadedModule[26]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System\e071297bb06faa961bef045ae5f25fdc\System.ni.dll
LoadedModule[27]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\21a1606b6c00f9abe7db55c02e0f87c9\System.Core.ni.dll
LoadedModule[28]=C:\Windows\assembly\NativeImages_v4.0.30319_32\WindowsBase\0d5a8e6f89227cc5d954e65856f9cf1a\WindowsBase.ni.dll
LoadedModule[29]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[30]=C:\Windows\system32\rsaenh.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_32\PresentationCore\e7873d3bd71f6122c2a954be1bb5bb28\PresentationCore.ni.dll
LoadedModule[32]=C:\Windows\assembly\NativeImages_v4.0.30319_32\Presentatio5ae0f00f#\b34cda03a984c515b31faf410e5b7e39\PresentationFramework.ni.dll
LoadedModule[33]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xaml\4d290752f65a065fcde70178562c3383\System.Xaml.ni.dll
LoadedModule[34]=C:\Windows\system32\dwrite.dll
LoadedModule[35]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[36]=C:\Windows\system32\MSVCP120_CLR0400.dll
LoadedModule[37]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[38]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[39]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[40]=C:\Windows\system32\RpcRtRemote.dll
LoadedModule[41]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\nlssorting.dll
LoadedModule[42]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\cd03f9386e02f56502e01a25ddd7e0a7\System.Configuration.ni.dll
LoadedModule[43]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\7c8f75f367134a030cba4a127dc62a2f\System.Xml.ni.dll
LoadedModule[44]=C:\Windows\system32\shell32.dll
LoadedModule[45]=C:\Windows\system32\profapi.dll
LoadedModule[46]=C:\Windows\system32\bcrypt.dll
LoadedModule[47]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\61dfb69c9ad6ed96809170d54d80b8a6\System.Drawing.ni.dll
LoadedModule[48]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\2dc6cfd856864312d563098f9486361c\System.Windows.Forms.ni.dll
LoadedModule[49]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=OnlyM
AppPath=C:\Program Files\OnlyM\OnlyM.exe

**Comment by Jemmuel13** [comment] 2019-01-15 23:53
@AntonyCorbett and the onlyM Slide Manager also works fine. btw thank you for technical assist..

**Comment by Jemmuel13** [comment] 2019-01-16 21:17
@AntonyCorbett sorry but I can't cause i don't have software to run the pre-release, and also I am not a programmer..

**Comment by AntonyCorbett** [comment] 2019-01-16 21:22
@Jemmuel13 the pre-release is a regular installation. It's just one that is not fully tested. Just go to the releases page and download / install as normal.

**Comment by AntonyCorbett** [comment] 2019-01-16 21:31
@Jemmuel13 great. I expect it will still fail to load on your machine, but there should be one short event log entry (in Windows Event Viewer) that tells us which file is missing.

**Comment by Jemmuel13** [comment] 2019-01-16 21:38
@AntonyCorbett the app won't run not even a message that pops-up but heres the event viewer says:

The description for Event ID 0 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.

the message resource is present but the message is not found in the string/message table

**Comment by AntonyCorbett** [comment] 2019-01-16 21:49
@Jemmuel13 that's just what I expected. The file that appears to be missing is CefSharp.Core.dll. This file should be in your OnlyM  installation folder. Please would you check?

**Comment by Jemmuel13** [comment] 2019-01-16 21:55
@AntonyCorbett yes the file is there.

**Comment by AntonyCorbett** [comment] 2019-01-16 22:01
Thanks. The missing file must be one of its dependencies. I'll go through the list and see what it might be. Is there anything unusual about your environment (other than Windows 7)?

**Comment by Jemmuel13** [comment] 2019-01-16 22:04
@AntonyCorbett thanks i believe nothing. because other app works fine..

**Comment by AntonyCorbett** [comment] 2019-01-18 10:18
@Jemmuel13 I think I would have to install a Windows 7 Home Premium environment in order to try to reproduce the problem, but since OnlyM is designed for Windows 10 I can't really justify the time to do this at the moment. Others have confirmed that they have it working on Win 7 so I suspect the problem has to do with a missing dependency of the CefSharp browser. A couple of suggestions before closing this issue:

1. Ensure that you have the latest .NET framework installed.
2. Install the MS Visual C++ runtime library 2015 (https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Closed** 2019-01-18 17:18 UTC
