### ISSUE TITLE
This is not a problem, but a workaround would be nice. 

### ISSUE THREAD

**Issue by al76543** [AntonyCorbett/OnlyM#261] opened 2019-05-25 02:42 UTC
Using pdf files of maps and "portrait" images works really well.
Our 2 auditoriums both have 2 monitors. The issue is that they are about 60 feet from the sound box. Moving the mouse across the second screen to click the "full screen" icon is a little distracting. Not to mention kind of hard for "older" eyes. How hard would it be to move the 3 screen controls on the secondary screens to the main screen.
Another thought is to have the same controls for images. (such as the full page image on page 18 of the March 2019 Watchtower.
Thanks for making mOnly available for the sound guys.

![Screenshot](https://user-images.githubusercontent.com/51011430/58363612-a5847580-7e6c-11e9-8cec-0f21ac010015.png)

**Comment by AntonyCorbett** [comment] 2019-05-25 13:57
@al76543 Why not use the "Mirror" function so that you see a duplicate of the media window on you primary display?

**Comment by al76543** [comment] 2019-05-25 21:04
Thanks, that should do it. My setup at home is using different size
monitors and the mirror function doesn't work well. I will try that in the
morning at the hall.
I have the extracted page 18 loaded into the media folder on both KH
computers.
Thanks again for your help.

**Comment by al76543** [comment] 2019-05-26 01:00
That fixed the issue. I was using an HP Envy laptop because of the touch
screen. I hooked up an old  Dell Precision laptop that has a 1080 screen
and it works fine. It doesn't have the touch screen, but the Lenovo
All-In-Ones at the hall do have.
Thanks again for the assistance.
al

**Closed** 2019-05-29 18:51 UTC
