### ISSUE TITLE
Windows 11 - Cannot Stop Media Playing

### ISSUE THREAD

**Issue by lunarpoodle** [AntonyCorbett/OnlyM#436] opened 2022-02-21 03:51 UTC
Hi Anthony,

I recently upgraded to Windows 11 Home - 
When I add video files to the media folder, I can hit "Play" - However, when I try to "stop" the playing - (by hitting the black square in the round green circle) - I am unable to stop the video.  I have to Ctrl+Alt+Del and kill the OnlyM program that way.

Please let me know if you know of a work around.
Thank you - 
- YB - Andrew Allen - Massachusetts USA -

**Comment by AntonyCorbett** [comment] 2022-02-22 18:17
@lunarpoodle Hi Andrew. Thanks for the report. Unfortunately, I can't reproduce the problem and searching through the Issues history, I can't find anything of a similar nature. Some questions, please:

1. Which version of OnlyM you are using? 
2. Does the problem occur with _all_ video files you have tried? 
3. Does it happen in both Media Foundation and Ffmpeg rendering modes?
4. Does it make any difference whether the media is in Windowed mode?
5. If you have multiple monitors, does it make a difference which monitor the media window is displayed on?

Kind regards
Antony

**Comment by lunarpoodle** [comment] 2022-02-23 18:25
Hello Antony,

Thank you for your reply!
Last night we went on to try out all your suggestions.

First, I got the *version : 2.0.0.12 *-
Secondly, I tried out a whole range of video / picture files to see if
indeed "*ALL FILES*" did not work..

The short version is that it all worked fine. Flawless. No problems.
I went back to the initial files that had caused the problem, and it worked
just fine.

I believe this issue must have been with Windows... maybe they put out an
update overnight? .. maybe it was a "Two's-Day" thing? (2/22/2022)...?
Whatever it was - it is no longer an issue.

How would you like me to update the issue I submitted?

Thanks,
Andrew

**Comment by AntonyCorbett** [comment] 2022-02-23 19:04
Hi Andrew. Thanks for testing. I'm glad it's working ok now, but it's a bit of a puzzle :) I'll close the issue.

Regards
Antony

**Closed by AntonyCorbett** 2022-02-23 19:04 UTC
